### ISSUE TITLE
Model Weights

### ISSUE THREAD

**Issue by amelie-iska** [CRIPAC-DIG/tgm-dlm#1]
Are the model weights for TGM-DLM available?

**Comment by Deno-V** [comment]
For your question, I still suggest that you run our code directly, as it can directly help you obtain the weight files for the two phases separately. I spent some time reorganizing the dataset at that time, but due to some unexpected circumstances, I have doubts about which one is the exact weight file from that time. If you have any other questions about the code and training, please feel free to continue communicating with me :)

**Comment by amelie-iska** [comment]
For retraining from scratch, what kind of hardware requirements are there? Also, approximately how many parameters does the full model have?

**Comment by JokerQianwei** [comment]
I reproduced the TGM-DLM code and ran the first stage for 120,000 steps (although it didn't reach the 200,000 timesteps in the paper, the evaluation results were very close). The model weights link is here:https://drive.google.com/file/d/1DOWYYeWbcNDuDaWnRJ73-IMypGw3GOOE/view?usp=sharing
